server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #限制文件上传大小
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 2501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 60
    height: 60
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.1.105:22122
    - 192.168.1.106:22122
jmall:
    upload:
        baseUrl: http://image.jmall.com/
        allowTypes:
          - image/png
          - image/jpeg
          - image/bmp